#builtin_box_drawing = true
live_config_reload = true
working_directory = "None"
ipc_socket = true

[env]
# brighter colors for tmux
TERM = "tmux-256color"

[window]
decorations = "full"
opacity = 0.9
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false
#option_as_alt = "None"

  [window.dimensions]
  columns = 120
  lines = 40

  [window.position]
  x = 0
  y = 0

  [window.padding]
  x = 0
  y = 0

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 16.5

  [font.normal]
  family = "IosevkaTerm Nerd Font Medium Extended"
  style = "extended"

  [font.bold]
  family = "IosevkaTerm Nerd Font ExtraBold Extended"
  style = "extended"

  [font.italic]
  family = "IosevkaTerm Nerd Font Medium Extended Obl"
  style = "extended Oblique"
  # [font.italics]
  # family = "monospace"
  # style = "Italics"

  # [font.bold_italics]
  # family = "monospace"
  # style = "Bold Italics"

  [font.offset]
  x = -1
  y = -2

  [font.glyph_offset]
  x = 0
  y = 0

[colors]
indexed_colors = [ ]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x00080F"
foreground = "0xabb2bf"
dim_foreground = "None"
bright_foreground = "0xe6efff"

[colors.cursor]
text = "0x000000"
cursor = "0x07EA00"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#000000"
background = "#ffffff"

[colors.search.focused_match]
foreground = "#ffffff"
background = "#000000"

#[colors.search.start]
#foreground = "#1d1f21"
#background = "#e9ff5e"
#
#[colors.search.end]
#foreground = "#e9ff5e"
#background = "#1d1f21"

[colors.line_indicator]
foreground = "None"
background = "None"

# [colors.footer_bar]
# background = "#c5c8c6"
# foreground = "#1d1f21"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"


[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
vi_mode_style = "None"
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "beam"
blinking = "on"

[shell]
program = "/bin/bash"

[hints]
alphabet = "jfkdls;ahgurieowpq"

  [[hints.enabled]]
    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    hyperlinks = true
    command = "xdg-open"
    post_processing = true

      [hints.enabled.mouse]
      enabled = true
      mods = "None"

      [hints.enabled.binding]
      key = "U"
      mods = "Control|Shift"

[debug]
render_timer = false
persistent_logging = false

[mouse]
hide_when_typing = false

#  [double_click]
#  threshold = 300
#
#  [triple_click]
#  threshold = 300

[[mouse.bindings]]
mouse = "Right"
action = "ExpandSelection"

[[mouse.bindings]]
mouse = "Right"
mods = "Control"
action = "ExpandSelection"

[[mouse.bindings]]
mouse = "Middle"
mode = "~Vi"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi|~Search"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "I"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Y"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "E"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "G"
mode = "Vi|~Search"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "G"
mods = "Shift"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "B"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "F"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "Copy"

[[keyboard.bindings]]
key = "Y"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Copy"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "V"
mode = "Vi|~Search"
action = "ToggleNormalSelection"

[[keyboard.bindings]]
key = "V"
mods = "Shift"
mode = "Vi|~Search"
action = "ToggleLineSelection"

[[keyboard.bindings]]
key = "V"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleBlockSelection"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
mode = "Vi|~Search"
action = "ToggleSemanticSelection"

[[keyboard.bindings]]
key = "Return"
mode = "Vi|~Search"
action = "Open"

[[keyboard.bindings]]
key = "Z"
mode = "Vi|~Search"
action = "CenterAroundViCursor"

[[keyboard.bindings]]
key = "K"
mode = "Vi|~Search"
action = "Up"

[[keyboard.bindings]]
key = "J"
mode = "Vi|~Search"
action = "Down"

[[keyboard.bindings]]
key = "H"
mode = "Vi|~Search"
action = "Left"

[[keyboard.bindings]]
key = "L"
mode = "Vi|~Search"
action = "Right"

[[keyboard.bindings]]
key = "Up"
mode = "Vi|~Search"
action = "Up"

[[keyboard.bindings]]
key = "Down"
mode = "Vi|~Search"
action = "Down"

[[keyboard.bindings]]
key = "Left"
mode = "Vi|~Search"
action = "Left"

[[keyboard.bindings]]
key = "Right"
mode = "Vi|~Search"
action = "Right"

[[keyboard.bindings]]
key = "Key0"
mode = "Vi|~Search"
action = "First"

[[keyboard.bindings]]
key = "Key4"
mods = "Shift"
mode = "Vi|~Search"
action = "Last"

[[keyboard.bindings]]
key = "Key6"
mods = "Shift"
mode = "Vi|~Search"
action = "FirstOccupied"

[[keyboard.bindings]]
key = "H"
mods = "Shift"
mode = "Vi|~Search"
action = "High"

[[keyboard.bindings]]
key = "M"
mods = "Shift"
mode = "Vi|~Search"
action = "Middle"

[[keyboard.bindings]]
key = "L"
mods = "Shift"
mode = "Vi|~Search"
action = "Low"

[[keyboard.bindings]]
key = "B"
mode = "Vi|~Search"
action = "SemanticLeft"

[[keyboard.bindings]]
key = "W"
mode = "Vi|~Search"
action = "SemanticRight"

[[keyboard.bindings]]
key = "E"
mode = "Vi|~Search"
action = "SemanticRightEnd"

[[keyboard.bindings]]
key = "B"
mods = "Shift"
mode = "Vi|~Search"
action = "WordLeft"

[[keyboard.bindings]]
key = "W"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRight"

[[keyboard.bindings]]
key = "E"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRightEnd"

[[keyboard.bindings]]
key = "Key5"
mods = "Shift"
mode = "Vi|~Search"
action = "Bracket"

[[keyboard.bindings]]
key = "Slash"
mode = "Vi|~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "Slash"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchBackward"

[[keyboard.bindings]]
key = "N"
mode = "Vi|~Search"
action = "SearchNext"

[[keyboard.bindings]]
key = "N"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchPrevious"

[[keyboard.bindings]]
key = "Return"
mode = "Search|Vi"
action = "SearchConfirm"

[[keyboard.bindings]]
key = "Escape"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "C"
mods = "Control"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Search"
action = "SearchClear"

[[keyboard.bindings]]
key = "W"
mods = "Control"
mode = "Search"
action = "SearchDeleteWord"

[[keyboard.bindings]]
key = "P"
mods = "Control"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "N"
mods = "Control"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Up"
mode = "Search"
action = "SearchHistoryPrevious"

[[keyboard.bindings]]
key = "Down"
mode = "Search"
action = "SearchHistoryNext"

[[keyboard.bindings]]
key = "Return"
mode = "Search|~Vi"
action = "SearchFocusNext"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
mode = "Search|~Vi"
action = "SearchFocusPrevious"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
mode = "~Vi"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
mode = "~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
mode = "~Search"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "NumpadSubtract"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "K"
mods = "Command"
mode = "~Vi|~Search"
chars = "\f"

[[keyboard.bindings]]
key = "K"
mods = "Command"
mode = "~Vi|~Search"
action = "ClearHistory"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "NumpadSubtract"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Command"
mode = "Vi|~Search"
action = "ClearSelection"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "Hide"

# [[keyboard.bindings]]
# key = "H"
# mods = "Command|Alt"
# action = "HideOtherApplications"

[[keyboard.bindings]]
key = "M"
mods = "Command"
action = "Minimize"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "Enter"
mods = "Shift|Control"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "F"
mods = "Command"
mode = "~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Command"
mode = "~Search"
action = "SearchBackward"

